name: siatma_mobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
 
  flutter:
    sdk: flutter
  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.13.0+2
  provider: ^4.3.3
  splash_screen_view: ^3.0.0
  bubble_tab_indicator: ^0.1.5
  ff_navigation_bar: ^0.1.5
  google_fonts: ^2.1.0  
  url_launcher: ^6.0.10
  shared_preferences: ^2.0.7
  line_awesome_icons: ^1.0.4+2
  carousel_slider: ^4.0.0
  auto_size_text: ^3.0.0
  shimmer: ^2.0.0
  simple_moment: ^1.1.1
  sliding_up_panel: ^2.0.0+1
  firebase_core: ^1.1.0
  firebase_messaging: ^11.2.5
  flutter_local_notifications: ^9.1.0
 

dev_dependencies:
 

  flutter_test:
    sdk: flutter


 
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec


  flutter_native_splash: ^1.2.0

flutter_native_splash:
    color: "#003c63"
    image: assets/images/UAJY_LOGOHD.png
    android_gravity: center
    ios_content_mode: center
    android: true
    ios: true

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/UAJY_Logo.png   
    - assets/images/UAJY_LOGOHD.png   
    - assets/images/LoginBack.png
    - assets/images/atma-logo.png
    - assets/images/decoration-blue-tip-2.png
    - assets/images/decoration-yellow.png
    - assets/images/nilai.png
    - assets/images/Nodata.png
    - assets/images/nilaiback.jpg
    - assets/images/presensi.png
    - assets/images/presensiback.jpg
    - assets/images/evaluasi.png
    - assets/images/evaluasiback.jpg
    - assets/images/bill.png
    - assets/images/billback.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Salsa
      fonts:
        - asset: assets/fonts/Salsa-Regular.ttf    
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf    
    - family: Fugaz
      fonts:
        - asset: assets/fonts/FugazOne-Regular.ttf    
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  

  